import type { NutritionTotals } from "@/lib/nutrition/types";

export type CatalogUnit =
  | "piece"
  | "cup"
  | "bowl"
  | "teaspoon"
  | "tablespoon"
  | "gram"
  | "ml"
  | "glass"
  | "slice"
  | "scoop";

export type CatalogFood = {
  id: string;
  name: string;
  aliases: string[];
  defaultAmount: number;
  defaultUnit: CatalogUnit;
  defaultLabel: string;
  nutrients: NutritionTotals;
  unitMultipliers: Partial<Record<CatalogUnit, number>>;
};

function totals(input: NutritionTotals): NutritionTotals {
  return input;
}

export const FOOD_CATALOG: CatalogFood[] = [
  {
    id: "chapati",
    name: "Chapati",
    aliases: ["chapati", "chapathi", "roti", "roti"],
    defaultAmount: 1,
    defaultUnit: "piece",
    defaultLabel: "1 piece",
    nutrients: totals({
      calories: 120,
      protein: 3.5,
      carbs: 18,
      fiber: 2.7,
      fat: 3.7,
      sugar: 0.6,
      water: 12,
      sodium: 120,
      calcium: 10,
      iron: 1.2,
      vitaminC: 0,
    }),
    unitMultipliers: { piece: 1 },
  },
  {
    id: "rice",
    name: "Cooked Rice",
    aliases: ["brown rice", "white rice", "cooked rice", "rice"],
    defaultAmount: 1,
    defaultUnit: "cup",
    defaultLabel: "1 cup",
    nutrients: totals({
      calories: 205,
      protein: 4.3,
      carbs: 45,
      fiber: 0.6,
      fat: 0.4,
      sugar: 0.1,
      water: 158,
      sodium: 1,
      calcium: 16,
      iron: 1.9,
      vitaminC: 0,
    }),
    unitMultipliers: { cup: 1, bowl: 1.2 },
  },
  {
    id: "dal",
    name: "Dal",
    aliases: ["dal tadka", "mixed dal", "dal fry", "dal"],
    defaultAmount: 1,
    defaultUnit: "bowl",
    defaultLabel: "1 bowl",
    nutrients: totals({
      calories: 160,
      protein: 9,
      carbs: 24,
      fiber: 7,
      fat: 3,
      sugar: 2.5,
      water: 115,
      sodium: 220,
      calcium: 35,
      iron: 2.5,
      vitaminC: 2,
    }),
    unitMultipliers: { bowl: 1, cup: 0.8 },
  },
  {
    id: "dal_makhani",
    name: "Dal Makhani",
    aliases: ["dal makhani", "dal makhni"],
    defaultAmount: 1,
    defaultUnit: "bowl",
    defaultLabel: "1 bowl",
    nutrients: totals({
      calories: 220,
      protein: 10,
      carbs: 23,
      fiber: 8,
      fat: 10,
      sugar: 3,
      water: 110,
      sodium: 320,
      calcium: 55,
      iron: 2.8,
      vitaminC: 3,
    }),
    unitMultipliers: { bowl: 1, cup: 0.8 },
  },
  {
    id: "paneer",
    name: "Paneer",
    aliases: ["paneer bhurji", "paneer", "cottage cheese"],
    defaultAmount: 100,
    defaultUnit: "gram",
    defaultLabel: "100 g",
    nutrients: totals({
      calories: 265,
      protein: 18,
      carbs: 6,
      fiber: 0,
      fat: 20,
      sugar: 3,
      water: 50,
      sodium: 22,
      calcium: 208,
      iron: 0.2,
      vitaminC: 0,
    }),
    unitMultipliers: { gram: 0.01 },
  },
  {
    id: "tofu",
    name: "Tofu",
    aliases: ["tofu"],
    defaultAmount: 100,
    defaultUnit: "gram",
    defaultLabel: "100 g",
    nutrients: totals({
      calories: 76,
      protein: 8,
      carbs: 1.9,
      fiber: 0.3,
      fat: 4.8,
      sugar: 0.6,
      water: 84,
      sodium: 7,
      calcium: 350,
      iron: 5.4,
      vitaminC: 0,
    }),
    unitMultipliers: { gram: 0.01 },
  },
  {
    id: "chicken_breast",
    name: "Chicken Breast",
    aliases: ["chicken breast", "grilled chicken", "chicken"],
    defaultAmount: 100,
    defaultUnit: "gram",
    defaultLabel: "100 g",
    nutrients: totals({
      calories: 165,
      protein: 31,
      carbs: 0,
      fiber: 0,
      fat: 3.6,
      sugar: 0,
      water: 65,
      sodium: 74,
      calcium: 15,
      iron: 0.9,
      vitaminC: 0,
    }),
    unitMultipliers: { gram: 0.01 },
  },
  {
    id: "chicken_curry",
    name: "Chicken Curry",
    aliases: ["chicken curry", "curry chicken"],
    defaultAmount: 1,
    defaultUnit: "bowl",
    defaultLabel: "1 bowl",
    nutrients: totals({
      calories: 250,
      protein: 22,
      carbs: 7,
      fiber: 2,
      fat: 15,
      sugar: 2,
      water: 120,
      sodium: 420,
      calcium: 35,
      iron: 1.5,
      vitaminC: 5,
    }),
    unitMultipliers: { bowl: 1, cup: 0.8 },
  },
  {
    id: "egg",
    name: "Egg",
    aliases: ["eggs", "egg"],
    defaultAmount: 1,
    defaultUnit: "piece",
    defaultLabel: "1 egg",
    nutrients: totals({
      calories: 72,
      protein: 6.3,
      carbs: 0.4,
      fiber: 0,
      fat: 4.8,
      sugar: 0.2,
      water: 38,
      sodium: 71,
      calcium: 28,
      iron: 0.9,
      vitaminC: 0,
    }),
    unitMultipliers: { piece: 1 },
  },
  {
    id: "egg_white",
    name: "Egg White",
    aliases: ["egg whites", "egg white"],
    defaultAmount: 1,
    defaultUnit: "piece",
    defaultLabel: "1 egg white",
    nutrients: totals({
      calories: 17,
      protein: 3.6,
      carbs: 0.2,
      fiber: 0,
      fat: 0.1,
      sugar: 0.2,
      water: 30,
      sodium: 55,
      calcium: 2,
      iron: 0,
      vitaminC: 0,
    }),
    unitMultipliers: { piece: 1 },
  },
  {
    id: "milk",
    name: "Milk",
    aliases: ["toned milk", "milk"],
    defaultAmount: 200,
    defaultUnit: "ml",
    defaultLabel: "200 ml",
    nutrients: totals({
      calories: 122,
      protein: 6.4,
      carbs: 9.6,
      fiber: 0,
      fat: 6.4,
      sugar: 10,
      water: 176,
      sodium: 90,
      calcium: 240,
      iron: 0.1,
      vitaminC: 0,
    }),
    unitMultipliers: { ml: 0.005, glass: 1, cup: 1 },
  },
  {
    id: "curd",
    name: "Curd",
    aliases: ["dahi", "curd", "yogurt"],
    defaultAmount: 100,
    defaultUnit: "gram",
    defaultLabel: "100 g",
    nutrients: totals({
      calories: 61,
      protein: 3.5,
      carbs: 4.7,
      fiber: 0,
      fat: 3.3,
      sugar: 4.7,
      water: 87,
      sodium: 46,
      calcium: 121,
      iron: 0.1,
      vitaminC: 0.5,
    }),
    unitMultipliers: { gram: 0.01, bowl: 1.5 },
  },
  {
    id: "greek_yogurt",
    name: "Greek Yogurt",
    aliases: ["greek yogurt", "greek yoghurt"],
    defaultAmount: 100,
    defaultUnit: "gram",
    defaultLabel: "100 g",
    nutrients: totals({
      calories: 97,
      protein: 9,
      carbs: 3.6,
      fiber: 0,
      fat: 5,
      sugar: 3.2,
      water: 80,
      sodium: 36,
      calcium: 110,
      iron: 0.1,
      vitaminC: 0,
    }),
    unitMultipliers: { gram: 0.01, bowl: 1.5 },
  },
  {
    id: "oats",
    name: "Oats",
    aliases: ["rolled oats", "oats", "oatmeal"],
    defaultAmount: 40,
    defaultUnit: "gram",
    defaultLabel: "40 g",
    nutrients: totals({
      calories: 154,
      protein: 5.3,
      carbs: 27,
      fiber: 4,
      fat: 2.7,
      sugar: 0.4,
      water: 3,
      sodium: 2,
      calcium: 21,
      iron: 1.8,
      vitaminC: 0,
    }),
    unitMultipliers: { gram: 0.025, cup: 2 },
  },
  {
    id: "whey",
    name: "Whey Protein",
    aliases: ["whey protein", "protein powder", "whey"],
    defaultAmount: 1,
    defaultUnit: "scoop",
    defaultLabel: "1 scoop",
    nutrients: totals({
      calories: 120,
      protein: 24,
      carbs: 3,
      fiber: 1,
      fat: 1.5,
      sugar: 2,
      water: 5,
      sodium: 60,
      calcium: 110,
      iron: 0.2,
      vitaminC: 0,
    }),
    unitMultipliers: { scoop: 1 },
  },
  {
    id: "banana",
    name: "Banana",
    aliases: ["banana"],
    defaultAmount: 1,
    defaultUnit: "piece",
    defaultLabel: "1 medium banana",
    nutrients: totals({
      calories: 105,
      protein: 1.3,
      carbs: 27,
      fiber: 3.1,
      fat: 0.4,
      sugar: 14,
      water: 89,
      sodium: 1,
      calcium: 6,
      iron: 0.3,
      vitaminC: 10.3,
    }),
    unitMultipliers: { piece: 1 },
  },
  {
    id: "apple",
    name: "Apple",
    aliases: ["apple"],
    defaultAmount: 1,
    defaultUnit: "piece",
    defaultLabel: "1 medium apple",
    nutrients: totals({
      calories: 95,
      protein: 0.5,
      carbs: 25,
      fiber: 4.4,
      fat: 0.3,
      sugar: 19,
      water: 156,
      sodium: 2,
      calcium: 11,
      iron: 0.2,
      vitaminC: 8.4,
    }),
    unitMultipliers: { piece: 1 },
  },
  {
    id: "orange",
    name: "Orange",
    aliases: ["orange"],
    defaultAmount: 1,
    defaultUnit: "piece",
    defaultLabel: "1 medium orange",
    nutrients: totals({
      calories: 62,
      protein: 1.2,
      carbs: 15.4,
      fiber: 3.1,
      fat: 0.2,
      sugar: 12.2,
      water: 131,
      sodium: 0,
      calcium: 52,
      iron: 0.1,
      vitaminC: 70,
    }),
    unitMultipliers: { piece: 1 },
  },
  {
    id: "bread",
    name: "Bread",
    aliases: ["bread slice", "bread", "toast"],
    defaultAmount: 1,
    defaultUnit: "slice",
    defaultLabel: "1 slice",
    nutrients: totals({
      calories: 80,
      protein: 3,
      carbs: 14,
      fiber: 1.2,
      fat: 1,
      sugar: 1.5,
      water: 10,
      sodium: 130,
      calcium: 40,
      iron: 0.9,
      vitaminC: 0,
    }),
    unitMultipliers: { slice: 1 },
  },
  {
    id: "peanut_butter",
    name: "Peanut Butter",
    aliases: ["peanut butter"],
    defaultAmount: 1,
    defaultUnit: "tablespoon",
    defaultLabel: "1 tablespoon",
    nutrients: totals({
      calories: 94,
      protein: 4,
      carbs: 3.2,
      fiber: 1.3,
      fat: 8,
      sugar: 1.7,
      water: 0.6,
      sodium: 70,
      calcium: 8,
      iron: 0.3,
      vitaminC: 0,
    }),
    unitMultipliers: { tablespoon: 1, teaspoon: 0.33 },
  },
  {
    id: "ghee",
    name: "Ghee",
    aliases: ["ghee"],
    defaultAmount: 1,
    defaultUnit: "teaspoon",
    defaultLabel: "1 teaspoon",
    nutrients: totals({
      calories: 45,
      protein: 0,
      carbs: 0,
      fiber: 0,
      fat: 5,
      sugar: 0,
      water: 0,
      sodium: 0,
      calcium: 0,
      iron: 0,
      vitaminC: 0,
    }),
    unitMultipliers: { teaspoon: 1, tablespoon: 3 },
  },
  {
    id: "sugar",
    name: "Sugar",
    aliases: ["sugar"],
    defaultAmount: 1,
    defaultUnit: "teaspoon",
    defaultLabel: "1 teaspoon",
    nutrients: totals({
      calories: 16,
      protein: 0,
      carbs: 4,
      fiber: 0,
      fat: 0,
      sugar: 4,
      water: 0,
      sodium: 0,
      calcium: 0,
      iron: 0,
      vitaminC: 0,
    }),
    unitMultipliers: { teaspoon: 1, tablespoon: 3 },
  },
  {
    id: "chai",
    name: "Chai",
    aliases: ["milk tea", "chai", "tea"],
    defaultAmount: 1,
    defaultUnit: "cup",
    defaultLabel: "1 cup",
    nutrients: totals({
      calories: 60,
      protein: 2,
      carbs: 7,
      fiber: 0,
      fat: 2.5,
      sugar: 6,
      water: 120,
      sodium: 40,
      calcium: 75,
      iron: 0.1,
      vitaminC: 0,
    }),
    unitMultipliers: { cup: 1, glass: 1.5, ml: 0.0063 },
  },
  {
    id: "coffee",
    name: "Black Coffee",
    aliases: ["black coffee", "coffee"],
    defaultAmount: 1,
    defaultUnit: "cup",
    defaultLabel: "1 cup",
    nutrients: totals({
      calories: 5,
      protein: 0.3,
      carbs: 0,
      fiber: 0,
      fat: 0,
      sugar: 0,
      water: 240,
      sodium: 5,
      calcium: 5,
      iron: 0,
      vitaminC: 0,
    }),
    unitMultipliers: { cup: 1, glass: 1.25, ml: 0.0042 },
  },
  {
    id: "poha",
    name: "Poha",
    aliases: ["poha"],
    defaultAmount: 1,
    defaultUnit: "bowl",
    defaultLabel: "1 bowl",
    nutrients: totals({
      calories: 250,
      protein: 5,
      carbs: 38,
      fiber: 3,
      fat: 8,
      sugar: 3,
      water: 100,
      sodium: 280,
      calcium: 20,
      iron: 1.2,
      vitaminC: 7,
    }),
    unitMultipliers: { bowl: 1, cup: 0.75 },
  },
  {
    id: "upma",
    name: "Upma",
    aliases: ["upma"],
    defaultAmount: 1,
    defaultUnit: "bowl",
    defaultLabel: "1 bowl",
    nutrients: totals({
      calories: 230,
      protein: 6,
      carbs: 36,
      fiber: 4,
      fat: 7,
      sugar: 3,
      water: 90,
      sodium: 260,
      calcium: 30,
      iron: 1.4,
      vitaminC: 6,
    }),
    unitMultipliers: { bowl: 1, cup: 0.75 },
  },
  {
    id: "idli",
    name: "Idli",
    aliases: ["idlis", "idli"],
    defaultAmount: 1,
    defaultUnit: "piece",
    defaultLabel: "1 idli",
    nutrients: totals({
      calories: 58,
      protein: 2,
      carbs: 12,
      fiber: 0.8,
      fat: 0.4,
      sugar: 0.2,
      water: 25,
      sodium: 60,
      calcium: 9,
      iron: 0.3,
      vitaminC: 0,
    }),
    unitMultipliers: { piece: 1 },
  },
  {
    id: "dosa",
    name: "Dosa",
    aliases: ["plain dosa", "dosa"],
    defaultAmount: 1,
    defaultUnit: "piece",
    defaultLabel: "1 dosa",
    nutrients: totals({
      calories: 168,
      protein: 4,
      carbs: 27,
      fiber: 1.5,
      fat: 5,
      sugar: 1.2,
      water: 50,
      sodium: 260,
      calcium: 18,
      iron: 1.1,
      vitaminC: 0,
    }),
    unitMultipliers: { piece: 1 },
  },
  {
    id: "paratha",
    name: "Paratha",
    aliases: ["paratha"],
    defaultAmount: 1,
    defaultUnit: "piece",
    defaultLabel: "1 paratha",
    nutrients: totals({
      calories: 260,
      protein: 6,
      carbs: 32,
      fiber: 4,
      fat: 12,
      sugar: 2,
      water: 20,
      sodium: 280,
      calcium: 20,
      iron: 1.6,
      vitaminC: 0,
    }),
    unitMultipliers: { piece: 1 },
  },
  {
    id: "rajma",
    name: "Rajma",
    aliases: ["rajma"],
    defaultAmount: 1,
    defaultUnit: "bowl",
    defaultLabel: "1 bowl",
    nutrients: totals({
      calories: 210,
      protein: 11,
      carbs: 30,
      fiber: 9,
      fat: 5,
      sugar: 3,
      water: 100,
      sodium: 300,
      calcium: 50,
      iron: 3.5,
      vitaminC: 4,
    }),
    unitMultipliers: { bowl: 1, cup: 0.8 },
  },
  {
    id: "chana_masala",
    name: "Chana Masala",
    aliases: ["chole", "chana masala", "chana"],
    defaultAmount: 1,
    defaultUnit: "bowl",
    defaultLabel: "1 bowl",
    nutrients: totals({
      calories: 230,
      protein: 10,
      carbs: 32,
      fiber: 8,
      fat: 7,
      sugar: 5,
      water: 100,
      sodium: 340,
      calcium: 60,
      iron: 4.2,
      vitaminC: 7,
    }),
    unitMultipliers: { bowl: 1, cup: 0.8 },
  },
  {
    id: "salad",
    name: "Salad",
    aliases: ["salad"],
    defaultAmount: 1,
    defaultUnit: "bowl",
    defaultLabel: "1 bowl",
    nutrients: totals({
      calories: 60,
      protein: 2,
      carbs: 12,
      fiber: 4,
      fat: 0.5,
      sugar: 6,
      water: 130,
      sodium: 70,
      calcium: 40,
      iron: 0.8,
      vitaminC: 18,
    }),
    unitMultipliers: { bowl: 1, cup: 0.75 },
  },
  {
    id: "almonds",
    name: "Almonds",
    aliases: ["almonds", "almond"],
    defaultAmount: 10,
    defaultUnit: "piece",
    defaultLabel: "10 almonds",
    nutrients: totals({
      calories: 70,
      protein: 2.6,
      carbs: 2.5,
      fiber: 1.5,
      fat: 6,
      sugar: 0.5,
      water: 1,
      sodium: 0,
      calcium: 28,
      iron: 0.4,
      vitaminC: 0,
    }),
    unitMultipliers: { piece: 0.1 },
  },
  {
    id: "sweet_potato",
    name: "Sweet Potato",
    aliases: ["sweet potato"],
    defaultAmount: 100,
    defaultUnit: "gram",
    defaultLabel: "100 g",
    nutrients: totals({
      calories: 86,
      protein: 1.6,
      carbs: 20.1,
      fiber: 3,
      fat: 0.1,
      sugar: 4.2,
      water: 77,
      sodium: 55,
      calcium: 30,
      iron: 0.6,
      vitaminC: 2.4,
    }),
    unitMultipliers: { gram: 0.01 },
  },
  {
    id: "water",
    name: "Water",
    aliases: ["water"],
    defaultAmount: 250,
    defaultUnit: "ml",
    defaultLabel: "250 ml",
    nutrients: totals({
      calories: 0,
      protein: 0,
      carbs: 0,
      fiber: 0,
      fat: 0,
      sugar: 0,
      water: 250,
      sodium: 0,
      calcium: 0,
      iron: 0,
      vitaminC: 0,
    }),
    unitMultipliers: { ml: 0.004, glass: 1, cup: 1 },
  },
  {
    id: "buttermilk",
    name: "Buttermilk",
    aliases: ["buttermilk", "chaas"],
    defaultAmount: 250,
    defaultUnit: "ml",
    defaultLabel: "250 ml",
    nutrients: totals({
      calories: 60,
      protein: 3,
      carbs: 6,
      fiber: 0,
      fat: 2,
      sugar: 5,
      water: 220,
      sodium: 180,
      calcium: 120,
      iron: 0,
      vitaminC: 0,
    }),
    unitMultipliers: { ml: 0.004, glass: 1, cup: 1 },
  },
];
